name: app-deploy-dev

on:
  workflow_dispatch:

jobs:
  app-deploy-dev:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout development branch
        uses: actions/checkout@v6.0.1
        with:
          ref: development

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::412433735452:role/org-development-role-iac-43dcbd2
          aws-region: us-east-1

      - name: Install hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.155.2'
          extended: true

      - name: Build
        run: hugo --environment development
        working-directory: ./TechBlog

      - name: Deploy
        run: hugo deploy --force --maxDeletes -1 --invalidateCDN --environment development
        working-directory: ./TechBlog
