name: app-deploy-prod

on:
  workflow_dispatch:

jobs:
  app-deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6.0.1

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::633067888675:role/org-production-role-iac-d53f9bb
          aws-region: us-east-1

      - name: Install hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.155.2'
          extended: true

      - name: Build
        run: hugo --environment production
        working-directory: ./PersonalWebsite.App

      - name: Deploy
        run: aws s3 sync --delete ./public s3://personal-website-bucket20241024190055276800000001
        working-directory: ./PersonalWebsite.App

      - name: Invalidate cdn
        run: aws cloudfront create-invalidation --distribution-id E2HMCICYT59BCK --paths "/*"
        working-directory: ./PersonalWebsite.App
