name: infra-preview-prod

on:
  workflow_dispatch:

jobs:
  infra-preview-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6.0.1

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run pulumi preview
        uses: pulumi/actions@v6.6.1
        with:
          command: preview
          stack-name: foflores/personal-website/prod
          work-dir: ./PersonalWebsite.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
