name: infra-deploy-dev

on:
  workflow_dispatch:

jobs:
  infra-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run pulumi update
        uses: pulumi/actions@v6
        with:
          command: update
          stack-name: foflores/hugoblog/dev
          work-dir: ./HugoBlog.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
